removed tooltips on date
hmcts/ccd-case-ui-toolkit pull request #1024
Opened 2022-02-11 14:41 UTC by sakanam

### JIRA link (https://tools.hmcts.net/jira/browse/EUI-2051) ###

### Change description ###
removed tooltip from dates in case description

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-02-11 15:06 UTC, RiteshHMCTS approved these changes, later dismissed

2022-02-14 10:36 UTC, Daniel-Lam reviewed
@sakanam - these changes look OK... are there any tests that need updating?

2022-02-14 10:39 UTC, rayliangatos commented on src/shared/components/palette/history/event-log/event-log-details.component.html
> +          <td><span class="text-16">{{event.user_first_name | titlecase}} {{event.user_last_name | uppercase}}</span></td>
A question, this div is for timestamp, but the behavior is now the sub item is changed to displaying firstName lastName, is that expected behavior? Given that this is a generic component, need to estimate the side effects.

2022-02-16 14:37 UTC, RiteshHMCTS approved these changes, later dismissed

2022-02-16 15:50 UTC, Daniel-Lam requested changes
@sakanam - please consider if there are any unit tests that need updating. Although not related to your change, one of the tests has been excluded by using `xit` - see https://github.com/hmcts/ccd-case-ui-toolkit/blob/e9bda7e74942c95f72c9fb46ed2a3e5690bc5eff/src/shared/components/palette/history/event-log/event-log-details.component.spec.ts#L111 It might be worth seeing if this test can be fixed and updated to reflect the removal of the tooltip.

2022-02-18 14:37 UTC, sakanam reviewed
@Daniel-Lam Updated test case to reflect removal of tooltip

2022-02-18 15:08 UTC, Daniel-Lam requested changes
@sakanam - just two very minor changes requested. Otherwise, the unit test looks fine.

2022-02-18 15:08 UTC, Daniel-Lam commented on src/shared/components/palette/history/event-log/event-log-details.component.spec.ts
>      let rows = de.queryAll($TABLE_ROWS);
@sakanam - although not part of your change, please change this to a `const` instead.

2022-02-18 15:08 UTC, Daniel-Lam commented on src/shared/components/palette/history/event-log/event-log-details.component.spec.ts
> +    let resultDate = new DatePipe(null).transform(EVENT.timestamp, 'local', null);
@sakanam - please change this to a `const` instead.

2022-02-18 15:22 UTC, Daniel-Lam approved these changes

2022-02-18 15:56 UTC, RiteshHMCTS approved these changes

2026-05-24 19:28 UTC, closed without merging