Bug/e UI 4702 postcode validation
hmcts/ccd-case-ui-toolkit pull request #1047
Opened 2022-03-01 08:56 UTC by phillip-whitaker-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-4702

### Change description ###

Added simple address postcode validation 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-01 09:18 UTC, RiteshHMCTS approved these changes

2022-03-01 10:10 UTC, Mo-Lala84 approved these changes
approved

2022-03-02 15:19 UTC, andywilkinshmcts requested changes
Don't merge this until we have consensus that this change won't have any unintended consequences

2022-05-31 09:16 UTC, phillip-whitaker-hmcts commented
This ticket has been withdrawn on recommendation from @andywilkinshmcts

2022-05-31 09:16 UTC, closed without merging