Remove mock
hmcts/ccd-case-ui-toolkit pull request #1213
Opened 2022-10-08 09:11 UTC by DavidJayakumar

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-6850

### Change description ###

Remove mock data dispaly

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-08 09:16 UTC, connorpgpmcelroy approved these changes

2022-10-08 09:17 UTC, connorpgpmcelroy requested changes
PR needs to be pointing at the correct branch

2022-10-08 09:17 UTC, MateiHMCTS approved these changes

2022-10-08 09:41 UTC, udaydenduluri33 commented
> PR needs to be pointing at the correct branch

We still need this PR to keep Release in Sync. So, please create another PR

2022-10-08 15:35 UTC, MateiHMCTS approved these changes

2022-10-14 10:51 UTC, DavidJayakumar commented
Wrong base branch

2022-10-14 10:51 UTC, closed without merging