bug/EUI-6975 case exclusion
hmcts/ccd-case-ui-toolkit pull request #1228
Opened 2022-10-24 11:24 UTC by Kartheek-S

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-6975

### Change description ###
User Excluded from case accessing same case via 16 digits reference within same session

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-10-24 12:33 UTC, udaydenduluri33 requested changes
Minor change - please introduce a function removeCachedCase in CaseNotifier instead if marking it to null

2022-10-24 12:50 UTC, MateiHMCTS commented on src/shared/components/case-editor/services/case.notifier.ts
> +    public removeCahedCase() {
typo

2022-10-24 13:52 UTC, udaydenduluri33 approved these changes

2022-10-25 09:17 UTC, DavidJayakumar approved these changes

2022-10-25 11:51 UTC, merged