EUI-7219 Case link unlink case name missing
hmcts/ccd-case-ui-toolkit pull request #1268
Opened 2022-11-29 12:09 UTC by johnbenjamin-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-7219

### Change description ###
Case name missing in UI even after adding from Service

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-11-29 18:19 UTC, Daniel-Lam requested changes
@johnbenjamin-hmcts - code changes are fine; you are just missing an entry in `RELEASE-NOTES.md` for the JIRA ticket number

2022-11-29 18:46 UTC, johnbenjamin-hmcts commented on RELEASE-NOTES.md
> +Linked cases private law integration
Thank you @Daniel-Lam - I have now updated the release note.

2022-11-29 23:00 UTC, Daniel-Lam approved these changes

2022-11-30 09:12 UTC, Kartheek-S approved these changes

2022-11-30 09:12 UTC, Kartheek-S commented on package.json
> +  "version": "4.20.27-linked-cases-private-law-integration",
package version is downgraded

2022-11-30 09:13 UTC, merged