7534 - Table header fix
hmcts/ccd-case-ui-toolkit pull request #1330
Opened 2023-01-20 17:21 UTC by cogrimes

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-7534

### Change description ###
Removed the th from the table

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-20 17:23 UTC, RiteshHMCTS submitted a review, later dismissed

2023-01-23 10:09 UTC, phillip-whitaker-hmcts approved these changes

2023-01-23 10:25 UTC, phillip-whitaker-hmcts requested changes
Removed nested table

2023-01-24 10:11 UTC, phillip-whitaker-hmcts approved these changes

2023-01-25 13:46 UTC, RiteshHMCTS approved these changes

2023-01-31 14:24 UTC, merged