Feature/e UI 7349
hmcts/ccd-case-ui-toolkit pull request #1338
Opened 2023-01-27 10:06 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-7349

### Change description ###
View and edit ‘Add Welsh translations to flag’

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-27 20:08 UTC, Daniel-Lam requested changes
@MateiHMCTS - just a few comments to address, all minor

2023-01-27 20:08 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
>            </textarea>
@MateiHMCTS - check alignment of `</textarea>` tag... it appears not to match indentation of the opening `<textarea>` tag

2023-01-27 20:08 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
> +      .compileComponents();
@MateiHMCTS - query indentation level...?

2023-01-27 20:08 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
> +  it('should set currentForm back to FLAG_FORM if it`s WELSH_TRANSLATION_FORM', () => {
@MateiHMCTS - would favour using a backslash to escape the single quote mark for `it's` (i.e. `it\'s`) rather than using the backtick

2023-01-30 10:31 UTC, johnbenjamin-hmcts approved these changes

2023-01-30 12:34 UTC, Daniel-Lam approved these changes

2023-03-01 12:33 UTC, merged