Feature/e UI 7605
hmcts/ccd-case-ui-toolkit pull request #1356
Opened 2023-02-13 10:01 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-7605

### Change description ###
Case File View Move takes a long time -- handle error and move allowMoving to false

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-13 14:31 UTC, johnbenjamin-hmcts submitted a review, later dismissed
@MateiHMCTS All looks good apart from one minor change. Approved.

2023-02-13 14:31 UTC, johnbenjamin-hmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.ts
> +      console.log(newCatId, node);
@MateiHMCTS - console.log statement

2023-02-13 14:48 UTC, GaryScottHMCTS approved these changes

2023-03-03 09:57 UTC, johnbenjamin-hmcts submitted a review, later dismissed

2023-03-03 10:52 UTC, Daniel-Lam requested changes
@MateiHMCTS - just a few function return types missing; otherwise OK

2023-03-03 10:52 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/case-file-view-field.component.ts
> +  public moveDocument(data: { document: DocumentTreeNode, newCategory: string }) {
@MateiHMCTS - function is missing a return type

2023-03-03 10:52 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/case-file-view-field.component.ts
> +  public reloadPage() {
@MateiHMCTS - function is missing a return type

2023-03-03 10:52 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/case-file-view-field.component.ts
> +  public resetErrorMessages() {
@MateiHMCTS - function is missing a return type

2023-03-03 11:32 UTC, Daniel-Lam submitted a review, later dismissed

2023-03-03 11:55 UTC, johnbenjamin-hmcts submitted a review, later dismissed

2023-03-03 14:07 UTC, Daniel-Lam approved these changes
@MateiHMCTS - re-approved

2023-03-03 14:14 UTC, johnbenjamin-hmcts approved these changes

2023-03-03 14:41 UTC, johnbenjamin-hmcts approved these changes

2023-03-03 14:44 UTC, Daniel-Lam submitted a review, later dismissed
@MateiHMCTS - re-approved again

2023-04-03 13:46 UTC, johnbenjamin-hmcts approved these changes

2023-04-06 00:00 UTC, merged