Feature/e UI 7368
hmcts/ccd-case-ui-toolkit pull request #1369
Opened 2023-02-24 12:04 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-7368

### Change description ###
Display & edit check your answers screen changes

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-02-24 13:41 UTC, johnbenjamin-hmcts approved these changes

2023-02-24 14:43 UTC, Kartheek-S approved these changes

2023-02-27 13:10 UTC, Daniel-Lam requested changes
@MateiHMCTS - small change required to how the event trigger ID is obtained

2023-02-27 13:10 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.html
> +                  <ng-container *ngIf="eventTrigger.id !== 'createCaseFlag' && eventTrigger.id !== 'requestSupport'">
@MateiHMCTS - this won't work if an HMCTS Service configures the event trigger ID to be something other than `createCaseFlag` or `requestSupport`. These values have come from the Definition file. The event trigger ID can be extracted from the URL. For example, in this URL: https://manage-case.aat.platform.hmcts.net/cases/case-details/1673960732219034/trigger/requestSupport/requestSupportRequestSupportFormPage, the trigger ID occurs after `trigger/` and before the last part of the path, i.e. `requestSupport`. Likewise, in this URL: https://manage-case.aat.platform.hmcts.net/cases/case-details/1673960732219034/trigger/updateCase/updateCaseSingleFormPage, the trigger ID is `updateCase`.

2023-03-01 15:19 UTC, merged