Feature/e UI 8112
hmcts/ccd-case-ui-toolkit pull request #1450
Opened 2023-05-11 08:21 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8112

### Change description ###
Query list display ticket

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-11 10:54 UTC, Daniel-Lam requested changes
@MateiHMCTS - small change needed to incorporate Welsh translation pipe

2023-05-11 10:54 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.html
> +      <th scope="col" class="govuk-table__header">Queries</th>
@MateiHMCTS - Lines 8 to 12 need to use the Welsh translation pipe, so it should look something like this: `{{'Queries' | rpxTranslate}}`

2023-05-11 14:42 UTC, DavidJayakumar submitted a review, later dismissed
LGTM

2023-05-11 15:07 UTC, Daniel-Lam submitted a review, later dismissed

2023-05-11 15:20 UTC, ronaldmansveld requested changes

2023-05-12 12:22 UTC, Daniel-Lam approved these changes
@MateiHMCTS - re-approved

2023-05-12 12:26 UTC, ronaldmansveld approved these changes

2023-05-16 15:25 UTC, merged