add translation pipe to form validation errors (firstError pipe and s…
hmcts/ccd-case-ui-toolkit pull request #1454
Opened 2023-05-16 11:15 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8361

### Change description ###
Added translation pipe to firstError and to other places where validation errors are shown

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-16 15:54 UTC, Daniel-Lam requested changes
@MateiHMCTS - only spotted one thing; the rest looks OK but I've also asked @ronaldmansveld to give it a once-over, too

2023-05-16 15:54 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
> +  public getRpxTranslatePipeArgs(fieldLabel: string) {
@MateiHMCTS - minor point; could do with a return type

2023-05-18 09:45 UTC, Daniel-Lam approved these changes

2023-05-18 16:07 UTC, DavidJayakumar approved these changes
LGTM

2023-05-30 14:47 UTC, merged