feature/EUI-8395
hmcts/ccd-case-ui-toolkit pull request #1460
Opened 2023-05-23 21:29 UTC by Kartheek-S

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8395

### Change description ###
Query Management - Update Response status column

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-05-24 09:51 UTC, Daniel-Lam requested changes
@Kartheek-S - one issue to address

2023-05-24 09:52 UTC, DavidJayakumar approved these changes
LGTM

2023-05-24 10:17 UTC, DavidJayakumar approved these changes

2023-05-24 11:00 UTC, Daniel-Lam approved these changes

2023-05-24 16:36 UTC, DavidJayakumar approved these changes

2023-06-27 09:12 UTC, MateiHMCTS commented
PR not in line with requirements

2023-06-27 09:12 UTC, closed without merging