Feature/e UI 8425
hmcts/ccd-case-ui-toolkit pull request #1462
Opened 2023-05-24 15:37 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8425

### Change description ###
Form validation errors

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-25 08:40 UTC, DavidJayakumar approved these changes
LGTM

2023-05-25 08:55 UTC, Daniel-Lam requested changes
@MateiHMCTS - really minor point on formatting but otherwise OK

2023-05-25 08:55 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/write-query-management-field.component.html
> +      {{ 'Next' | rpxTranslate}}
@MateiHMCTS - minor point on spacing of `rpxTranslate` and `}}`; same on Line 69

2023-05-25 14:00 UTC, Daniel-Lam submitted a review, later dismissed
@MateiHMCTS - looks good now; approved

2023-05-25 15:27 UTC, DavidJayakumar approved these changes

2023-06-05 16:10 UTC, DavidJayakumar commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-management-error-messages/query-management-error-messages.component.html
> +    {{'There is a problem' | rpxTranslate}}
space after and before braces {{ }}

2023-06-05 16:12 UTC, DavidJayakumar reviewed
@MateiHMCTS Please see my comments

2023-06-05 16:12 UTC, DavidJayakumar reviewed
@MateiHMCTS Please see my comments

2023-06-05 16:17 UTC, MateiHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/write-query-management-field.component.ts
> +
True; Forgot about this as this was done a while ago.

2023-06-15 11:06 UTC, closed without merging