Feature/e UI 8379
hmcts/ccd-case-ui-toolkit pull request #1471
Opened 2023-06-02 14:33 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8379

### Change description ###
Document uploader in write query views

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-06-06 15:16 UTC, Daniel-Lam requested changes
@MateiHMCTS - just one minor observation; the rest is OK

2023-06-06 15:16 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-raise-query/query-write-raise-query.component.html
> +            <span class="govuk-visually-hidden">{{ 'Error:' | rpxTranslate }}</span> {{ 'Enter a body' |
@MateiHMCTS - I think this error message should probably read `Enter a query body` as opposed to `Enter a body`

2023-06-06 16:44 UTC, DavidJayakumar approved these changes
LGTM

2023-06-07 09:26 UTC, DavidJayakumar approved these changes
Looks good

2023-06-07 09:30 UTC, Daniel-Lam submitted a review, later dismissed

2023-06-12 16:10 UTC, Daniel-Lam approved these changes
@MateiHMCTS - this change with the `display_context` value looks fine; approved

2023-06-12 16:20 UTC, merged