Feature/EUI 8454
hmcts/ccd-case-ui-toolkit pull request #1476
Opened 2023-06-07 16:09 UTC by DavidJayakumar

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-8454
https://tools.hmcts.net/jira/browse/EUI-8387

### Change description ###

Follow up query display

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-06-08 11:49 UTC, MateiHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html
> +            {{ context === 'Responded' ? 'Response message' : 'Query Body' | rpxTranslate }}
Please use the enum values in the template instead of another string

2023-06-08 12:15 UTC, Daniel-Lam requested changes
@DavidJayakumar - some changes needed

2023-06-08 12:15 UTC, Daniel-Lam commented on package.json
> +  "version": "6.16.0-query-management-fowllow-up-v1",
@DavidJayakumar - minor point on spelling: `follow-up-v1`

2023-06-08 12:15 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/package.json
> +  "version": "6.16.0-query-management-fowllow-up-v1",
@DavidJayakumar - minor point on spelling: `follow-up-v1`

2023-06-08 12:15 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html
> +      {{ context === 'Responded' ? 'Respond to a query' : 'Ask a follow-up question' | rpxTranslate }}
@DavidJayakumar - similar to @MateiHMCTS's comment, please use the enum value instead of the string `'Responded'`

2023-06-08 12:15 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
> +    <dl *ngIf="context === 'Responded'" class="govuk-summary-list govuk-!-margin-bottom-0">
@DavidJayakumar - similar to @MateiHMCTS's comment, please use the enum value instead of the string `'Responded'`

2023-06-08 12:15 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
> +          {{ context === 'Responded' ? 'Response message' : 'Query body' | rpxTranslate }}
@DavidJayakumar - similar to @MateiHMCTS's comment, please use the enum value instead of the string `'Responded'`

2023-06-08 13:51 UTC, Daniel-Lam approved these changes

2023-06-08 15:12 UTC, MateiHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
> +  @Input() public context: string;
Can you please make it so context's type is QueryItemType?

2023-06-08 15:14 UTC, MateiHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
> +  @Input() public context: string;
Also optionally... I would change either 'context' or QueryItemType so they match. Maybe QueryCreateContext?

2023-06-08 16:18 UTC, MateiHMCTS submitted a review, later dismissed

2023-06-09 09:01 UTC, Daniel-Lam approved these changes
@DavidJayakumar - approved

2023-06-13 16:16 UTC, MateiHMCTS approved these changes

2023-06-13 19:18 UTC, merged