Feature/e UI 8483
hmcts/ccd-case-ui-toolkit pull request #1477
Opened 2023-06-07 16:45 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8483

### Change description ###
Add full name

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-06-08 09:22 UTC, Daniel-Lam approved these changes
@MateiHMCTS - approved

2023-06-08 09:29 UTC, DavidJayakumar requested changes
Error message is incorrect

2023-06-08 09:29 UTC, DavidJayakumar commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html
> +          <span class="govuk-visually-hidden">{{ 'Error:' | rpxTranslate }}</span> {{ 'Enter a message' | rpxTranslate }}
@MateiHMCTS Error message should be 'Enter your fullname'.

2023-06-08 09:40 UTC, DavidJayakumar approved these changes
LGTM

2023-06-08 09:43 UTC, Daniel-Lam approved these changes
@MateiHMCTS - re-approved

2023-06-13 12:29 UTC, DavidJayakumar submitted a review, later dismissed

2023-06-13 12:35 UTC, johnbenjamin-hmcts submitted a review, later dismissed

2023-06-13 12:35 UTC, Daniel-Lam approved these changes
@MateiHMCTS - approved

2023-06-14 11:23 UTC, DavidJayakumar submitted a review, later dismissed
Looks good

2023-06-14 11:43 UTC, johnbenjamin-hmcts approved these changes

2023-06-14 11:58 UTC, johnbenjamin-hmcts approved these changes

2023-06-14 12:18 UTC, merged