Feature/e UI 8451
hmcts/ccd-case-ui-toolkit pull request #1489
Opened 2023-06-14 09:02 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8451

### Change description ###
CYA Raise a query

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-06-16 12:11 UTC, DavidJayakumar requested changes

2023-06-16 12:11 UTC, DavidJayakumar commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
> +          {{ formGroup.get('hearingDate')?.value | date: 'dd/MM/yyyy' }}
Date format should be 'dd MMM yyyy'

2023-06-16 15:32 UTC, DavidJayakumar approved these changes
Looks good

2023-06-19 15:48 UTC, Daniel-Lam submitted a review, later dismissed
@MateiHMCTS - all looks good here; approved

2023-06-21 10:27 UTC, DavidJayakumar submitted a review, later dismissed

2023-06-28 10:37 UTC, johnbenjamin-hmcts approved these changes

2023-06-28 10:40 UTC, DavidJayakumar submitted a review, later dismissed

2023-06-28 11:14 UTC, DavidJayakumar approved these changes

2023-06-28 11:14 UTC, merged