Feature/e UI 8455
hmcts/ccd-case-ui-toolkit pull request #1501
Opened 2023-06-22 09:01 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8455

### Change description ###
Display multiple responses and follow up

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-06-22 16:22 UTC, johnbenjamin-hmcts approved these changes

2023-06-22 16:31 UTC, DavidJayakumar submitted a review, later dismissed
Looks good

2023-06-23 13:33 UTC, DavidJayakumar approved these changes
Looks good

2023-06-26 15:27 UTC, johnbenjamin-hmcts approved these changes

2023-06-26 15:57 UTC, DavidJayakumar requested changes
@MateiHMCTS Just one comment

2023-06-26 15:57 UTC, DavidJayakumar commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.html
> +      <p class="govuk-!-font-weight-bold">Your query is under review</p>
Doesn't have translation

2023-06-26 16:18 UTC, johnbenjamin-hmcts submitted a review, later dismissed

2023-06-26 16:19 UTC, DavidJayakumar submitted a review, later dismissed
@MateiHMCTS Looks good

2023-06-28 09:56 UTC, DavidJayakumar approved these changes
LGTM

2023-06-28 10:03 UTC, johnbenjamin-hmcts approved these changes

2023-06-28 10:03 UTC, merged