EUI-8526
hmcts/ccd-case-ui-toolkit pull request #1502
Opened 2023-06-23 11:47 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8526

### Change description ###
Hide name input on raise query/respond to a query/ follow-up query

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-06-26 10:18 UTC, johnbenjamin-hmcts submitted a review, later dismissed

2023-06-26 10:53 UTC, DavidJayakumar approved these changes

2023-06-28 13:56 UTC, johnbenjamin-hmcts requested changes
Just one comment about the design.

2023-06-28 13:56 UTC, johnbenjamin-hmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/qualifying-questions/qualifying-question-options/qualifying-question-options.component.html
> +          <ng-container *ngIf="isLast">
@MateiHMCTS there is no hr line based on the Figma I referred to https://www.figma.com/proto/uGkmgQzZWmHJYq7w6Y8ACa/Query-Management-Prototype-Latest-May-2023?page-id=783%3A72991&type=design&node-id=1061-88834&viewport=724%2C374%2C0.07&scaling=min-zoom&starting-point-node-id=1061%3A88834

Let us check with Tommy regarding this.

2023-06-28 14:37 UTC, DavidJayakumar approved these changes
LGTM

2023-06-28 14:38 UTC, merged