ExUI-623 Secure Document Store mode doesn't work properly during case creation(v2)
hmcts/ccd-case-ui-toolkit pull request #1551
Opened 2023-08-23 14:05 UTC by andywilkinshmcts

### JIRA link (if applicable) ###
EXUI-623

### Change description ###
Jurisdiction Service needs to publish currently selected jurisdiction and case type as a BehaviorSubject

**Does this PR introduce a breaking change?** (check one with "x")

[ ] Yes
[x] No
```

2023-09-05 15:42 UTC, Daniel-Lam requested changes
@andywilkinshmcts - a few `console` statements that could be removed

2023-09-05 15:42 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
> +    console.info('writeDocumentField.ngInit: secure mode = ' + this.secureModeOn);
@andywilkinshmcts - could probably remove this `console` statement

2023-09-05 15:42 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
> +        console.info(`caseNotifier.next: caseType=${this.caseTypeId} juris=${this.jurisdictionId}`)
@andywilkinshmcts - could probably remove this `console` statement

2023-09-05 15:42 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
> +        console.info(`selectedJurisdiction.next: caseType=${this.caseTypeId} juris=${this.jurisdictionId}`)
@andywilkinshmcts - could probably remove this `console` statement

2023-09-05 15:42 UTC, Daniel-Lam commented on projects/ccd-case-ui-toolkit/src/lib/shared/services/jurisdiction/jurisdiction.service.ts
> +    console.info ('Announcing selected jurisdiction = ' + jurisdiction?.id);
@andywilkinshmcts - could probably remove this `console` statement

2023-09-14 11:27 UTC, Daniel-Lam requested changes
@andywilkinshmcts @RiteshHMCTS - Sonarcloud still reporting insufficient test coverage of 31.2%

2023-09-18 14:16 UTC, Daniel-Lam reviewed
@andywilkinshmcts - approved but with the caveat that the test coverage on new code is still too low at 17.3% (even though after merge the overall coverage will be 81.0%). Not great because merging this will bring the overall coverage down

2023-09-18 14:17 UTC, Daniel-Lam approved these changes

2023-09-20 10:01 UTC, RiteshHMCTS approved these changes

2023-09-20 12:48 UTC, merged