initial fix for document upload problems
hmcts/ccd-case-ui-toolkit pull request #1599
Opened 2023-10-20 16:58 UTC by andywilkinshmcts

**Before creating a pull request make sure that:**

- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###
Fix to issue caused by cases with many document collections. A bit of research lead me to this:
https://stackoverflow.com/questions/52108773/handling-multiple-components-with-click-events-in-angular
Which points out as an aside that having a hostlistener causes additional change detection cycles. When I checked we do have such a host listener. It doesn't look as though it's adding much value - looks like it it's just setting the error message if the user clicks on the page. 
The same SO post suggests a way of doing this without host listener, which we could try if the functionality is necessary

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-10-23 10:38 UTC, OgunyemiO approved these changes

2023-10-23 10:41 UTC, RiteshHMCTS requested changes
@andywilkinshmcts change the version in below file too
projects/ccd-case-ui-toolkit/package.json

2023-11-09 11:26 UTC, RiteshHMCTS approved these changes

2023-11-09 17:02 UTC, kasi-subramaniam approved these changes

2023-11-09 17:03 UTC, OgunyemiO approved these changes

2023-11-09 17:04 UTC, merged