Error message for wrong file type refactored.
hmcts/ccd-case-ui-toolkit pull request #1619
Opened 2023-11-21 12:50 UTC by OgunyemiO

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EXUI-1038

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-21 15:03 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
> +      errorMsg = obj.error;
if (obj && obj?.error) {
  errorMsg = obj.error
}

2023-11-21 15:03 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
> +    let errorMsg = null;
let errorMsg = 'Error uploading file';

2023-11-21 15:05 UTC, andywilkinshmcts requested changes
Need to improve the error handling

2023-11-21 15:05 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
> +      const start = fullError.indexOf('{');
Need to check that the error message actually contains some json:
if (start >= 0) {

2023-11-21 15:16 UTC, OgunyemiO commented
> Need to improve the error handling

@andywilkinshmcts Done!

2023-11-24 12:28 UTC, olusegz07 submitted a review, later dismissed

2023-11-27 10:01 UTC, andywilkinshmcts submitted a review, later dismissed

2024-01-11 11:52 UTC, merged