remove dynamic list field if value is null frm CYA
hmcts/ccd-case-ui-toolkit pull request #1648
Opened 2023-12-20 17:04 UTC by RiteshHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-1137

### Change description ###
Additional details appearing on preview screen for hearing

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-12-20 17:16 UTC, andywilkinshmcts requested changes
Maybe rewrite as I have suggested for clarity, and check what length you need to test if it's a dynamic list

2023-12-20 17:16 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/ccd-read-fields-filter.pipe.ts
> +      ReadFieldsFilterPipe.EMPTY_VALUES.indexOf(value.value) !== -1 : ReadFieldsFilterPipe.EMPTY_VALUES.indexOf(value) !== -1;
Kinda nasty - had to read it a few times to spot why you have ReadFieldsFilterPipe.EMPTY_VALUES.indexOf() twice
maybe just do this 
const fieldValue = value?.list_items && value?.value ? value.value : value;
const valueIsEmpty =  ReadFieldsFilterPipe.EMPTY_VALUES.indexOf(fieldValue);
return valueIsEmpty || fieldValue.length == 0;

2023-12-20 17:16 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/ccd-read-fields-filter.pipe.ts
> +    return valueIsEmpty || value.length === 0;
Is it appropriate to test value.length if you have a dynamic list?

2023-12-21 11:54 UTC, richardhenryash approved these changes

2023-12-21 15:34 UTC, olusegz07 approved these changes

2024-01-11 12:36 UTC, merged