Csfd 15 ungrey back button
hmcts/ccd-case-ui-toolkit pull request #1706
Opened 2024-03-26 10:40 UTC by joeevanshmcts

### JIRA link (if applicable) ###

- [Epic Link](https://tools.hmcts.net/jira/browse/CSFD-14)
- [CSFD-8](https://tools.hmcts.net/jira/browse/CSFD-8)
- [CSFD-9](https://tools.hmcts.net/jira/browse/CSFD-9)
- [CSFD-15](https://tools.hmcts.net/jira/browse/CSFD-15)
- [CSFD-16](https://tools.hmcts.net/jira/browse/CSFD-16)
- [CSFD-17](https://tools.hmcts.net/jira/browse/CSFD-17)

### Change Description ###
I've included the epic above to show how there are other items of work associated to this. The purpose of this pull request is to ensure that the existing changes get pushed into master, while they're not 100% complete, they're an improvement on what is currently there in production as of the time of writing this. There are _still_ some issues with the implementation, it's not perfect, but it is an improvement. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2024-07-23 08:40 UTC, andywilkinshmcts submitted a review, later dismissed
Minor change - nice to fix but not essential

2024-07-24 09:04 UTC, olusegz07 submitted a review, later dismissed

2024-08-08 11:02 UTC, connorpgpmcelroy approved these changes
Approved with minor comment

2024-08-08 11:11 UTC, OgunyemiO approved these changes

2024-08-08 12:40 UTC, RiteshHMCTS submitted a review, later dismissed

2024-09-06 14:47 UTC, connorpgpmcelroy requested changes
Minor query

2024-09-06 14:47 UTC, connorpgpmcelroy commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
> +    console.log(this.multipageComponentStateService.getInstigator());
Is console.log necessary here?

2024-09-09 08:13 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
> +    console.log(this.multipageComponentStateService.getInstigator());
Gd spot, will remove

2024-09-09 16:29 UTC, connorpgpmcelroy approved these changes
LGTM

2025-01-29 13:04 UTC, connorpgpmcelroy requested changes
Lots of minor comments and a few moderate ones. Quite a long PR  and not necessarily my expertise in the application but looks like most of it is good and functional.

2025-01-29 14:04 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
> +      if (linkedCasesTab && linkedCasesTab?.value.length !== initalLinks.length){
Added additional checks for properties

2025-01-29 14:05 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
> +import exp from 'constants';
Moved imports and removed unused imports

2025-01-29 14:06 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
> +    it('should remove any unsibmitted data on cancel', () => {
Fixed

2025-01-29 14:13 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.spec.ts
> +    router.getCurrentNavigation.and.returnValue({ previousNavigation: { finalUrl: '/cases/case-details/1707912713167104#Claim%20details' } });
Updated to const

2025-01-29 14:16 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
> +import { cloneDeep } from 'lodash';
Moved

2025-01-29 14:21 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
> +  public cachedControls;
Typed

2025-01-29 14:22 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
> +    let originalPathToFlag;
Typed

2025-01-29 15:12 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts
> +import { MultipageComponentStateService } from '../../../../../services';
Moved

2025-01-29 15:14 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
> +  public handleBackButtonSubJourney(event) {
Updated types and returns throughout this file

2025-01-29 15:18 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
> +      if (this.cachedFlagType.Path.length === 1) {
Done

2025-01-29 15:19 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
> +  public validateTranslationNeeded(){
Done

2025-01-29 15:20 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/read-case-flag-field.component.ts
> +            (this.caseFlagStateService.formGroup.get('selectedManageCaseLocation').value.flagDetailDisplay && this.displayContextParameter === CaseFlagDisplayContextParameter.UPDATE_2_POINT_1))) {
Moved to a const

2025-01-29 15:21 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/read-case-flag-field.component.ts
> +  private cleanupNavigationFormAdditions(selectedFlagsLocation: FlagsWithFormGroupPath){
Done

2025-01-29 15:23 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/before-you-start/before-you-start.component.ts
> +  public next() {
Not sure why it was done like this, have simplified to one next function

2025-01-29 15:24 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.ts
> +import { Router } from '@angular/router';
Moved

2025-01-29 15:24 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.ts
> +    super(multipageComponentStateService);
bumped ) { to next line

2025-01-29 15:25 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.ts
> +    const trigUrl = location.href;
Valid point, renamed to trigger

2025-01-29 15:50 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.ts
> +    if (this.linkedCasesPage === 0){
Done a search through the changes and updated all instances of ){

2025-01-29 15:52 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
> +      // if they cancel on the last CYA page we should ensure there is no unsubmitted data in the caseDetails
Split to child functions

2025-01-29 15:53 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
> +    if (this.isLinkedCasesJourney()){
I have moved it to its own reset function

2025-02-04 14:43 UTC, connorpgpmcelroy submitted a review, later dismissed
Looks a lot better and more consistent, will approve, please see further comments to make small further editions

2025-02-04 14:46 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
> +    it('should remove any unsibmitted data on cancel', () => {
Resolved

2025-02-04 14:47 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
> +import { CaseTab } from 'ccd-case-ui-toolkit';
resolved

2025-02-10 12:26 UTC, RiteshHMCTS submitted a review, later dismissed

2025-02-10 12:26 UTC, RiteshHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/link-cases/link-cases.component.ts
> +      return initialCaseLinks.includes(proposedCaseLink);
@Josh-HMCTS can you remove these console.log

2025-02-10 12:26 UTC, RiteshHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/unlink-cases/unlink-cases.component.ts
> +    console.log(journeyPageNumber, linkedCasesPageNumber)
@Josh-HMCTS same here if we don't need it then we can remove it.

2025-02-10 12:26 UTC, RiteshHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
> +    console.log('validateTranslateNeeded');
@Josh-HMCTS  if we don't need this console.log, then remove it.

2025-02-10 14:14 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/link-cases/link-cases.component.ts
> +      return initialCaseLinks.includes(proposedCaseLink);
removed

2025-02-10 14:15 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/unlink-cases/unlink-cases.component.ts
> +    console.log(journeyPageNumber, linkedCasesPageNumber)
removed

2025-02-10 14:15 UTC, Josh-HMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
> +    console.log('validateTranslateNeeded');
removed

2025-03-12 16:54 UTC, olusegz07 approved these changes

2025-03-12 16:55 UTC, merged