sort sub documents by recent uploads first
hmcts/ccd-case-ui-toolkit pull request #1725
Opened 2024-05-10 09:42 UTC by OgunyemiO

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EXUI-1858

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-05-13 09:31 UTC, RiteshHMCTS submitted a review, later dismissed

2024-05-13 10:09 UTC, andywilkinshmcts requested changes

2024-05-13 10:09 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.spec.ts
> -    expect(component.documentTreeData).toEqual(treeData);
I understand why you've removed this check, but you should replace it with something. For example you could check that the first item is the appropriately sorted first item

2024-05-14 10:06 UTC, andywilkinshmcts submitted a review, later dismissed

2024-05-14 14:22 UTC, RiteshHMCTS submitted a review, later dismissed

2024-06-25 08:09 UTC, Josh-HMCTS approved these changes

2024-06-25 09:12 UTC, andywilkinshmcts approved these changes

2024-07-03 10:35 UTC, RiteshHMCTS approved these changes

2024-07-04 10:05 UTC, connorpgpmcelroy approved these changes
LGTM

2024-07-04 10:07 UTC, merged