EXUI-1735 - Case hyperlink for case consolidated
hmcts/ccd-case-ui-toolkit pull request #1729
Opened 2024-05-21 12:52 UTC by Josh-HMCTS

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EXUI-1735?src=confmacro

### Change description ###

Add case hyperlink to 'linked from' table when link reason is 'case consolidated'

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2024-05-22 11:44 UTC, RiteshHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/linked-cases-table/linked-cases-from-table.component.ts
> +  }
@Josh-HMCTS can you add some unit tests for these functions

2024-05-23 10:51 UTC, RiteshHMCTS submitted a review, later dismissed

2024-05-28 17:00 UTC, andywilkinshmcts requested changes
Chopping off the link seems like a hack. Would like to understand better why it's necessary

2024-05-31 13:34 UTC, olusegz07 approved these changes

2024-06-04 14:38 UTC, andywilkinshmcts approved these changes

2024-06-04 14:39 UTC, andywilkinshmcts approved these changes

2024-06-25 14:31 UTC, RiteshHMCTS approved these changes

2024-06-25 15:12 UTC, merged