Commit full client context changes
hmcts/ccd-case-ui-toolkit pull request #1733
Opened 2024-05-30 14:00 UTC by connorpgpmcelroy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-1838
https://tools.hmcts.net/jira/browse/EXUI-1839
https://tools.hmcts.net/jira/browse/EXUI-1840

### Change description ###
Replace take to be completed in session storage with new client context object

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2024-06-03 11:25 UTC, RiteshHMCTS submitted a review, later dismissed

2024-06-04 14:07 UTC, andywilkinshmcts requested changes
Looks good apart from one v minor typo

2024-06-05 09:30 UTC, connorpgpmcelroy commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/cases.service.spec.ts
> +      expect(httpService.post).toHaveBeenCalledWith(VALIDATE_CASE_URL, CASE_EVENT_DATA, { headers, observe: 'response' as 'bodu' });
Edited, great spot

2024-06-05 09:33 UTC, andywilkinshmcts submitted a review, later dismissed

2024-09-10 09:52 UTC, Josh-HMCTS submitted a review, later dismissed

2024-09-10 09:59 UTC, connorpgpmcelroy commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/event-completion-state-machine.service.ts
> +    console.log('clienht cintedt ', clientContextStr)
will remove

2024-09-10 10:00 UTC, connorpgpmcelroy commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
> +      // const task: Task = JSON.parse(taskStr);
yes we can

2024-09-10 10:50 UTC, RiteshHMCTS approved these changes

2024-09-10 10:51 UTC, Josh-HMCTS approved these changes

2024-09-10 10:51 UTC, merged