Update search-result.component.html
hmcts/ccd-case-ui-toolkit pull request #1737
Opened 2024-06-06 13:40 UTC by olusegz07

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-06-06 13:46 UTC, RiteshHMCTS approved these changes

2024-06-06 13:48 UTC, andywilkinshmcts requested changes

2024-06-06 13:48 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/search-result/search-result.component.html
> +            Select All
This should be "Select all" - style guide is to use Sentence case, not Title Case

2024-06-06 13:48 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/search-result/search-result.component.html
> +              Select Case Reference {{ result.case_id }}
This should be "Select case" not "Select Case Reference". You are not selecting the reference, you are selecting the case, and it should be in sentence case.

2024-06-06 13:48 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/search-result/search-result.component.html
> +              Select Case Reference {{ result.case_id }}
Same as previous comment

2024-06-10 08:34 UTC, StoneBenHMCTS submitted a review, later dismissed

2024-06-25 08:05 UTC, Josh-HMCTS approved these changes

2024-06-25 09:56 UTC, andywilkinshmcts approved these changes

2024-06-27 08:40 UTC, OgunyemiO approved these changes

2024-06-27 10:37 UTC, andywilkinshmcts submitted a review, later dismissed

2024-07-02 09:55 UTC, OgunyemiO approved these changes

2024-08-01 13:48 UTC, closed without merging