Exui-2007-show-warning
hmcts/ccd-case-ui-toolkit pull request #1741
Opened 2024-06-19 11:58 UTC by RiteshHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-2007

### Change description ###
show warning before event and task completion journey

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-06-21 11:12 UTC, andywilkinshmcts requested changes
Please confirm that you have manually tested the following 2 scenarios:
Task A assigned to user 1
User 1 starts event
User 2 reassigns Task A to User 2
User 1 submits event

and

Task A assigned to user 1
User 1 starts event
User 2 marks Task A as done
User 1 submits event

2024-07-01 10:02 UTC, andywilkinshmcts submitted a review, later dismissed
Change is fine, but additional work needed to resolve the scenarios I mentioned

2024-07-09 15:31 UTC, kasi-subramaniam approved these changes

2024-07-09 15:34 UTC, olusegz07 approved these changes

2024-07-09 15:39 UTC, merged