Add the necessary details to session storage
hmcts/ccd-case-ui-toolkit pull request #1755
Opened 2024-07-31 14:51 UTC by connorpgpmcelroy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-2148

### Change description ###
Add the necessary details to session storage (user ID, timestamp in addition in new object)

2024-08-02 08:48 UTC, RiteshHMCTS approved these changes

2024-08-02 12:55 UTC, OgunyemiO submitted a review, later dismissed

2024-08-02 14:37 UTC, andywilkinshmcts requested changes

2024-08-02 15:49 UTC, connorpgpmcelroy commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
> +      return true;
Will make change to it

2024-08-05 10:46 UTC, RiteshHMCTS submitted a review, later dismissed

2024-08-05 11:13 UTC, Josh-HMCTS submitted a review, later dismissed

2024-08-22 09:02 UTC, andywilkinshmcts requested changes
Fix typo in package.json - info not inf0

2024-09-25 14:41 UTC, merged