exui-2220-add logs
hmcts/ccd-case-ui-toolkit pull request #1763
Opened 2024-08-20 10:50 UTC by RiteshHMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-2220

### Change description ###
add logs

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-08-23 08:15 UTC, andywilkinshmcts approved these changes

2024-08-23 10:45 UTC, andywilkinshmcts submitted a review, later dismissed

2024-08-23 10:45 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts
> +      this.appConfig.logMessage(`search for completable call missed for ${caseId} in event ${eventId}`);
Can you change this message to "isWAEnabled false for ${caseId} in event {eventId}"

2024-08-23 10:45 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts
> +    console.log(`isWAEnabled: ${ftstr}`);
You could remove the console.log

2024-08-23 13:14 UTC, RiteshHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts
> +    console.log(`isWAEnabled: ${ftstr}`);
done

2024-08-29 13:39 UTC, andywilkinshmcts requested changes

2024-08-29 13:39 UTC, andywilkinshmcts commented on package.json
> +  "version": "7.0.58-exui-2220-rc4",
Version number needs to be updated to 7.0.61

2024-08-29 13:44 UTC, Josh-HMCTS approved these changes

2024-08-29 14:50 UTC, Josh-HMCTS approved these changes

2024-08-29 14:53 UTC, merged