EXUI-1108: Update to yarn v4.5.0
hmcts/ccd-case-ui-toolkit pull request #1782
Opened 2024-10-10 09:56 UTC by Josh-HMCTS

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EXUI-1108

### Change description ###

Update yarn to v4.5.0, update yarn audit sh script to work with new yarn audit format

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2024-10-15 11:26 UTC, RiteshHMCTS approved these changes

2024-10-15 15:00 UTC, connorpgpmcelroy submitted a review, later dismissed
LGTM

2024-10-15 16:08 UTC, andywilkinshmcts requested changes
Good effort but let's discuss possible changes

2024-10-15 16:23 UTC, Josh-HMCTS commented on bin/run-yarn-audit.sh
> +diff_output=$(diff "$upToDateVulnerabilities" "$vulnerabilitiesInRepo")
Yeah good point, i will update this to check the return code and not store the diff output

2024-10-15 16:26 UTC, Josh-HMCTS commented on bin/run-yarn-audit.sh
> +if [[ -n "$diff_output" ]]; then
I'll update the -n to just use the return code as part of above change
Ill just remove the diff output from the print as i dont think it really adds anything as anyone who sees its failed will just run the command again not use the diff output to manually update it

2024-10-18 10:07 UTC, olusegz07 approved these changes

2024-10-28 14:24 UTC, andywilkinshmcts approved these changes

2024-10-28 14:26 UTC, merged