Bug/ex UI 2431 special characters crashing
hmcts/ccd-case-ui-toolkit pull request #1798
Opened 2024-10-24 13:55 UTC by connorpgpmcelroy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-2431

### Change description ###
Edit special characters before they are encoded to ensure there are no errors with non-ASCII characters

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2024-10-25 11:14 UTC, RiteshHMCTS submitted a review, later dismissed

2024-10-28 09:21 UTC, andywilkinshmcts requested changes
Let's talk about this at the 3 amigos

2024-10-28 14:44 UTC, andywilkinshmcts requested changes
Happy with basic approach, but a couple more minor changes

2024-10-28 14:44 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-utils/case-edit.utils.ts
> +  // Note: Made these purposely odd to avoid possible data conflicts
This comment is now incorrect

2024-10-28 14:44 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-utils/case-edit.utils.ts
> +    return rawString ? rawString.replace(/[^\x20-\x7F]/g, function (c) {
Sorry to be annoying, but I think that 0x7F is a control character (Delete) so it should be replaced - this should be /[^\x20-\x7E]/

2024-10-29 09:49 UTC, andywilkinshmcts requested changes

2024-10-29 09:49 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/cases.service.ts
> +      clientContextEdit.client_context.user_task.task_data.name = 'Review ㅪ the ㋚ appeal \`';
Is this left over debug code?

2024-10-30 09:41 UTC, andywilkinshmcts approved these changes

2024-12-03 14:16 UTC, merged