#EXUI-1832: 'Choose file' and 'no file chosen' not being sent via Wesh translation API
hmcts/ccd-case-ui-toolkit pull request #1800
Opened 2024-10-29 12:09 UTC by MunishSharmaHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-1832

### Change description ###
 'Choose file' and 'no file chosen' not being sent via Wesh translation API

Re-design looks like : 

![image](https://github.com/user-attachments/assets/65313f52-52c7-42b0-8a77-be131dc1f1fe)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-10-29 12:35 UTC, olusegz07 submitted a review, later dismissed

2024-10-29 13:55 UTC, RiteshHMCTS submitted a review, later dismissed

2025-01-30 15:04 UTC, andywilkinshmcts requested changes

2025-01-30 15:04 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.html
> +        <span>{{fileName | rpxTranslate}}</span>
Don't translate the file name

2025-01-30 17:06 UTC, MunishSharmaHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.html
> +        <span>{{fileName | rpxTranslate}}</span>
done

2025-02-04 09:52 UTC, StoneBenHMCTS approved these changes

2025-02-04 09:53 UTC, andywilkinshmcts approved these changes

2025-06-04 09:48 UTC, merged