exui-2469-hidden field should be removed from event submittion
hmcts/ccd-case-ui-toolkit pull request #1802
Opened 2024-10-30 17:46 UTC by RiteshHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-2469

### Change description ###
hidden field should be removed from event submittion

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-10-31 08:57 UTC, MunishSharmaHMCTS approved these changes

2024-10-31 09:23 UTC, connorpgpmcelroy approved these changes
LGTM

2024-10-31 09:24 UTC, connorpgpmcelroy requested changes
Sonar failures

2024-10-31 16:40 UTC, MunishSharmaHMCTS submitted a review, later dismissed

2024-11-01 11:18 UTC, connorpgpmcelroy submitted a review, later dismissed
LGTM

2024-11-01 12:11 UTC, andywilkinshmcts approved these changes

2024-11-01 12:11 UTC, andywilkinshmcts commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/valid-page-list-caseFields.service.ts
> +        page.case_fields.forEach(field => {
I did this refactor for you

2024-11-01 12:23 UTC, RiteshHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/valid-page-list-caseFields.service.ts
> +        page.case_fields.forEach(field => {
thanks @andywilkinshmcts

2024-11-12 10:11 UTC, andywilkinshmcts approved these changes

2024-12-03 14:37 UTC, merged