exui-2536-issue-with-dynamic-multi-select-list
hmcts/ccd-case-ui-toolkit pull request #1813
Opened 2024-11-20 17:02 UTC by RiteshHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-2536

### Change description ###
issue-with-dynamic-multi-select-list

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-11-21 10:56 UTC, MunishSharmaHMCTS approved these changes

2024-11-22 10:10 UTC, andywilkinshmcts requested changes
I think you should expand this code to also handle the other 2 dynamic list types FIELD_TYPE_DYNAMIC_LIST
FIELD_TYPE_DYNAMIC_RADIO_LISTt
The change looks as though it could be applied to the other types too. I would write a function isDynamicList ( fieldType => fieldType == FieldTypeSanitizer.whatever || fieldType == otherwhat || fieldType == wibble)

2024-11-25 17:54 UTC, andywilkinshmcts approved these changes
Thanks for extending the code to cover all the cases, but I'd prefer it if you wrote an "isDynamicField" function

2024-11-26 11:59 UTC, RiteshHMCTS commented on projects/ccd-case-ui-toolkit/src/lib/shared/services/form/field-type-sanitiser.ts
> +        FieldTypeSanitiser.DYNAMIC_LIST_TYPE.indexOf(complexField.field_type.type) !== -1 &&
moved to function

2024-12-03 14:45 UTC, merged