EUI-1620 - date display format
hmcts/ccd-case-ui-toolkit pull request #577
Opened 2020-09-07 11:36 UTC by andywilkinshmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-1620

### Change description ###
Implement date formatting for display of dates.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```
Backwards compatibility maintained, as evidenced by the tests. However there was a mostly non-functional date parameter on the date pipe which now works as expected. Any code which called the date pipe passing a date format will now get most likely get a different result. However no service code currently does this.

2020-09-07 11:44 UTC, adnanakgun requested changes
I believe you are missing the updated yarn.lock file. Everything else seems fine.

2020-09-07 11:51 UTC, Daniel-Lam requested changes
@andywilkinshmcts - just the one comment on timezone identifier. Also, do you have tests that check the correct behaviour when the time is transitioning from GMT to BST (from 00:59 GMT going forward to 02:00 BST) on the last Sunday in March and vice versa (from 01:59 BST going back to 01:00 GMT) on the last Sunday in October?

2020-09-07 11:51 UTC, Daniel-Lam commented on src/shared/components/palette/utils/date.pipe.ts
> +        resultDate = formatDate(offsetDate, format, 'en-UK', null)
I thought the timezone was `en-GB`? Might be inconsequential but thought I'd check

2020-09-08 22:16 UTC, Daniel-Lam approved these changes
@andywilkinshmcts - nice work on the additional unit tests 👍, approved.

2020-09-23 09:18 UTC, merged