EUI-2350 dynamic lists in complex types
hmcts/ccd-case-ui-toolkit pull request #612
Opened 2020-11-25 17:25 UTC by adnanakgun

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-2530

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-11-26 10:50 UTC, andywilkinshmcts requested changes
Looks reasonable, but should probably be commented more to indicate why, and the limitations of the fix

2020-11-26 17:39 UTC, udaydenduluri33 commented on src/shared/components/case-editor/services/cases.service.ts
> +      jsonResponse.case_fields.forEach(caseField => {
'COMPLEX' as const?

2020-11-27 12:12 UTC, udaydenduluri33 approved these changes

2020-11-27 12:30 UTC, andywilkinshmcts approved these changes

2020-12-02 15:06 UTC, closed without merging