Feature/e UI 2015 pagination accessibility Phillip Hhitaker
hmcts/ccd-case-ui-toolkit pull request #651
Opened 2021-01-11 10:13 UTC by phillip-whitaker

https://tools.hmcts.net/jira/browse/EUI-2015

### Change description ###

The change provides a new component - <ccd-pagination> which adds additional markup to the existing pagination for accessibility requirements. 

Additionally, work has been done to ensure that ID attributes are unique throughout the jurisdiction process. There were a couple of instances where dumb components were using fixed IDs that when multiple instances existed in one page it failed 4.1.1 parsing

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-01-11 10:39 UTC, phillip-whitaker commented on src/shared/components/palette/address/write-address-field.component.ts
I have moved `createId `into the abstract class as it is used by multiple components and created a new `buildIdPrefix ` method for dynamic inner components in the write-address-field

2021-01-11 11:42 UTC, adnanakgun approved these changes

2021-01-11 13:55 UTC, paul-graham requested changes

2021-01-11 13:55 UTC, paul-graham commented on src/shared/components/pagination/pagination.component.html
> +</pagination-template>
Line feed needed at the end.

2021-01-11 13:55 UTC, paul-graham commented on src/shared/components/pagination/pagination.component.scss
> +.ngx-pagination li {
Why is this not in the block above?

2021-01-11 13:55 UTC, paul-graham commented on src/shared/components/pagination/pagination.component.scss
> +.ngx-pagination a:hover,
Seeing as this is a .scss file, this could be nested in the above block.

2021-01-11 13:55 UTC, paul-graham commented on src/shared/components/pagination/pagination.component.scss
> +.ngx-pagination .disabled:hover {
Again, nested in the above block.

2021-01-11 13:55 UTC, paul-graham commented on src/shared/components/pagination/pagination.component.ts
> +    @Input()
4 space indenting? It's 2 in lines 8 to 10 and should be 2 throughout for consistency.

2021-01-11 13:55 UTC, paul-graham commented on src/shared/components/palette/address/write-address-field.component.ts
> +    return this.idPrefix + '_' + elementId ;
A string literal would be better here, rather than concatenation.

2021-01-11 13:55 UTC, paul-graham commented on src/shared/components/palette/base-field/abstract-field-write.component.ts
> +    return this.id() + '_' + elementId ;
Again, string literal. :)

2021-01-11 13:55 UTC, paul-graham commented on tsconfig-aot.json
> +    "outDir": "dist",
I'd guess at a linting error for whitespace on the end of a line.

2021-01-11 15:12 UTC, paul-graham submitted a review, later dismissed
All seems to be in order. 👍

2021-01-11 15:17 UTC, paulhowes-HMCTS submitted a review, later dismissed
Looks good now other review recommendations have been implemented.

2021-04-08 08:51 UTC, phillip-whitaker commented
updated with master

2021-04-08 09:25 UTC, paulhowes-HMCTS submitted a review, later dismissed
Looks fine again.

2021-04-27 14:56 UTC, paul-graham submitted a review, later dismissed
Previously approved. Went stale. Now back from the dead and looking to paginate a component near you soon... but this time, it's _personal_!

2021-04-27 15:29 UTC, paul-graham approved these changes
Simply repointed. 👍

2021-04-27 15:33 UTC, paulhowes-HMCTS submitted a review, later dismissed
Previously approved. Reapproving due to the branch going stale and now being risen from the dead.

2021-05-19 10:33 UTC, rayliangatos approved these changes

2021-05-19 10:54 UTC, rayliangatos approved these changes

2021-05-19 10:54 UTC, merged