Feature/e UI 2831 multi select dynamic phillip whitaker
hmcts/ccd-case-ui-toolkit pull request #722
Opened 2021-03-09 16:15 UTC by phillip-whitaker

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-2831

### Change description ###

Create Multiselect checkbox input value

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-03-10 15:21 UTC, paul-graham requested changes

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.component.spec.ts
> +    it('render values as a table with one row and one cell per value', () => {
Additionally, can we have some tests for the _other_ `value` structure - the one where it's an object that contains an array of `list_items` and an array of `value` objects?

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.component.spec.ts
> +    it('render values as a table with one row and one cell per value', () => {
This might actually be only for the write fields... not sure.

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.html
> +  </table>
Indenting peculiarity in here...

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/multi-select-list.scss
> +.multi-select-list-field-table {
Should this be called `read-dynamic-multi-select-list-field.component.scss` since that's the only place it's used?

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/write-dynamic-multi-select-list-field.component.spec.ts
> +  it('should mark as selected the initially selected checkboxes', () => {
Add a test for when the value is null and/or a single item, rather than all items?

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/write-dynamic-multi-select-list-field.component.ts
> +      // Remove the control form the FormArray
"from"

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/write-dynamic-multi-select-list-field.component.ts
> +  isSelected(code): AbstractControl {
The `code` parameter should have a type. `: string`, presumably...?

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/write-dynamic-multi-select-list-field.component.ts
> +  onCheckChange(event) {
The `event` parameter should have a type...

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/dynamic-multi-select-list/write-dynamic-multi-select-list-field.html
> +          <input class="form-control" id="{{ buildElementId(checkbox.code) }}" [name]="id()" type="checkbox" [value]="checkbox.code" [checked]="isSelected(checkbox.code)" (change)="onCheckChange($eve
Can `[name]="id()"` be replaced with `name="{{ id() }}"` like you've done for the `id` attribute? :)

2021-03-10 15:21 UTC, paul-graham commented on src/shared/components/palette/palette.service.ts
> +         return write ? WriteDynamicListFieldComponent : ReadDynamicListFieldComponent;
Indenting is off.

2021-03-11 14:45 UTC, paul-graham approved these changes
Thank you for making the requested changes, @phillip-whitaker, and answering my annoying questions. Happy to approve this now. 👍

2021-03-11 15:38 UTC, paulhowes-HMCTS requested changes
A few finicky amends

2021-03-11 15:38 UTC, paulhowes-HMCTS commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.component.scss
> +      padding: 5px 0 5px 0;
Does this require linting? Also I believe 5px 0 would suffice.

2021-03-11 15:38 UTC, paulhowes-HMCTS commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.component.scss
> +      padding: 5px 0 5px 0;
Just 5px 0?

2021-03-11 15:38 UTC, paulhowes-HMCTS commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.component.spec.ts
> +    it('render values as a table with one row and one cell per value', () => {
For readability - 'should render values ...

2021-03-11 15:38 UTC, paulhowes-HMCTS commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.component.spec.ts
> +    it('render some values as a table with one row and one cell per value', () => {
'should render

2021-03-11 15:38 UTC, paulhowes-HMCTS commented on src/shared/components/palette/dynamic-multi-select-list/read-dynamic-multi-select-list-field.component.spec.ts
> +    let FieldReadComponent = MockComponent({
const?

2021-03-11 15:38 UTC, paulhowes-HMCTS commented on src/shared/components/palette/dynamic-multi-select-list/write-dynamic-multi-select-list-field.html
> +        <span class="form-label" *ngIf="caseField.label">{{caseField | ccdFieldLabel}}</span>
Being finicky again but for readability can class="form-label" be moved after the ngIf as per the next two lines

2021-03-11 15:38 UTC, paulhowes-HMCTS commented on src/shared/components/palette/palette.service.ts
> +        // return write ? WriteDynamicListFieldComponent : ReadDynamicListFieldComponent;
Remove commented out code if not required

2021-03-11 16:31 UTC, paulhowes-HMCTS submitted a review, later dismissed
Fine now comments have been resolved

2023-02-28 15:49 UTC, Kartheek-S commented
Changes are there in PR 1174 and this PR has no package file changes. So, closing this PR

2023-02-28 15:49 UTC, closed without merging