MoneyGBP issue
hmcts/ccd-case-ui-toolkit pull request #780
Opened 2021-05-11 10:53 UTC by paul-graham

### JIRA link (if applicable) ###
N/A, but issue identified here: https://github.com/hmcts/ccd-case-ui-toolkit/pull/618

### Change description ###
Fixed an issue with how `MoneyGBP` fields are rendered as it failed to render correctly for a numeric value of zero and could also weirdly stringify a return value because of the return type.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-05-11 10:54 UTC, phillip-whitaker approved these changes

2021-05-11 11:06 UTC, phillip-whitaker approved these changes

2021-05-11 11:27 UTC, Daniel-Lam requested changes
@paul-graham - review completed; just one small change required... have a guess what it might be ;)

2021-05-11 11:27 UTC, Daniel-Lam commented on src/shared/services/fields/fields.utils.ts
> +        let fieldValue = (result[field.id] || result[field.id] === 0) ? result[field.id] : field.value;
Can't `let` this one go :)

2021-05-11 11:40 UTC, Daniel-Lam commented on src/shared/services/fields/fields.utils.ts
> +        let fieldValue = (result[field.id] || result[field.id] === 0) ? result[field.id] : field.value;
Haha, I'll bet! 😛

2021-05-11 11:40 UTC, Daniel-Lam approved these changes

2021-05-12 16:07 UTC, rayliangatos approved these changes

2021-06-17 13:43 UTC, merged