defaulted hidden state for added complex fields in collection to false
hmcts/ccd-case-ui-toolkit pull request #804
Opened 2021-06-09 03:40 UTC by phillip-whitaker

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-3983

### Change description ###

#### The Issue
When a collection that contains complex fields is added as part of a collection the fields with show condition are momentarily displayed before the `conditional-show-form.directive.ts` kicks in and hides it. This is because the subscription has a debounce(100) on it. The debounce is there to help performance.

#### The Fix
As I saw it, there are two fixes to this bug, remove the debounce or default added collection complex fields to hidden = true for fields that have show_condition logic. I chose the latter because I think is more sustainable and I know that the show/hide logic all being changed soon too so this fix will withstand the changes to the current directive.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x-x-x] No
```

2021-06-09 07:00 UTC, Mo-Lala84 approved these changes
lgtm

2021-06-09 08:06 UTC, paul-graham reviewed
Just a question around the filtering mechanism...

2021-06-09 08:06 UTC, paul-graham commented on src/shared/components/palette/collection/write-collection-field.component.ts
> +        .filter((cf: CaseField) => cf.show_condition !== null)
Do we know for sure this is always `null` when it's not set? It's never `undefined` or `''`? `!!cf.show_condition` would account for all of those, which might be a better option.

2021-06-09 09:10 UTC, paul-graham requested changes

2021-06-09 09:10 UTC, paul-graham commented on src/shared/components/palette/collection/write-collection-field.component.ts
> +        .filter((cf: CaseField) => !cf.show_condition)
This should be a double bang, not a single. You're filtering out anything _with_ a `show_condition` now! 😂

2021-06-09 09:16 UTC, paul-graham approved these changes
Sorted. Thanks for fixing the double bang, @phillip-whitaker.

2021-06-18 15:34 UTC, paul-graham submitted a review, later dismissed

2021-06-28 09:29 UTC, paul-graham approved these changes

2021-06-28 11:09 UTC, merged