Release 4.1.0
hmcts/ccd-case-ui-toolkit pull request #819
Opened 2021-06-15 12:14 UTC by ernestman28

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-06-30 16:20 UTC, paul-graham requested changes
Just reviewed the `RELEASE-NOTES.md`. Not going to review beyond that at this point.

2021-06-30 16:20 UTC, paul-graham commented on RELEASE-NOTES.md
> -### Version 4.0.0
It kinda looks like you've ditched everything to do with `Version 4.0.0`, which seems like a bad idea.

2021-06-30 16:22 UTC, paul-graham commented on package.json
> +  "version": "4.1.0-rc.3",
If we're merging into `master`, this shouldn't have the suffix.

2021-06-30 16:25 UTC, paul-graham requested changes
This merge has gone badly. It's reverting fixes and causing regressions. I'm now considering this to be terminal as I _strongly_ suspect there will be other regressions too!

2021-06-30 16:25 UTC, paul-graham commented on src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
> +  public generateErrorMessage(fields: CaseField[]): void {
Everything in this method is 100% wrong. This undoes all the fixes @RiteshHMCTS put in place!

2021-07-01 10:42 UTC, paul-graham requested changes
Clearly the merge into `release-4.1.0` went very wrong as this is now looking to _remove_ a bunch of fixes from `master`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/date/write-date-field.html
> +    <span class="error-message" *ngIf="dateControl && dateControl.errors && dateControl.touched">{{dateControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression - it should be using `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/date/write-date-field.html
> +                    [isInvalid]="dateControl.errors && dateControl.touched"
This is a regression - it should be using `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.html
> +            *ngIf="dateControl && dateControl.errors && dateControl.touched && !(this.minError || this.maxError)">{{dateControl.errors | ccdFirstError:caseField.label}}</span>
Not a regression as it's the same in `master` but this should definitely be using `dirty` and not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.html
> +            *ngIf="dateControl && dateControl.touched && this.minError">This date is older than the minimum date allowed</span>
Also `dirty`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.html
> +            *ngIf="dateControl && dateControl.touched && this.maxError">This date is later than the maximum date allowed</span>
Also `dirty`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.html
> +             (focusout)="focusOut()"
This is a regression: `(focusout)` was recently removed in `master`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.ts
> +  public focusOut(): void {
This is a regression: `focusOut()` was recently removed in `master`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.ts
> +import { FormControl, Validators } from '@angular/forms';
I'm a bit nervous about this component at the moment as it looks like there were extensive changes on both `master` and `release-4.1.0` so it needs more investigation... and will probably need some regression testing.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/email/write-email-field.html
> +  <span class="error-message" *ngIf="emailControl.errors && emailControl.touched">{{emailControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/email/write-email-field.html
> +  <input class="form-control" [ngClass]="{'govuk-input--error': emailControl.errors && emailControl.touched}"
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/fixed-list/write-fixed-list-field.html
> +  <span class="error-message" *ngIf="fixedListFormControl.errors && fixedListFormControl.touched">{{fixedListFormControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/fixed-list/write-fixed-list-field.html
> +    <span class="form-label" *ngIf="caseField.label">{{caseField | ccdFieldLabel}}</span>
Reintroduction of pointless whitespace is a regression.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/fixed-radio-list/write-fixed-radio-list-field.html
> +      <span class="error-message" *ngIf="fixedRadioListControl.errors && fixedRadioListControl.touched">{{fixedRadioListControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/fixed-radio-list/write-fixed-radio-list-field.html
> +        <span class="form-label" *ngIf="caseField.label">{{caseField | ccdFieldLabel}}</span>
Whitespace reintroduction.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/money-gbp/write-money-gbp-field.html
> +  <span class="error-message" *ngIf="moneyGbpControl.errors && moneyGbpControl.touched">{{moneyGbpControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/multi-select-list/write-multi-select-list-field.html
> +      <span class="form-label" *ngIf="caseField.label">{{caseField | ccdFieldLabel}}</span>
Whitespace reintroduction.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/multi-select-list/write-multi-select-list-field.html
> +    <span *ngIf="checkboxes.errors && checkboxes.touched" class="error-message">{{checkboxes.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/number/write-number-field.html
> +  <span class="error-message" *ngIf="numberControl.errors && numberControl.touched">{{numberControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/number/write-number-field.html
> +  <input class="form-control bottom-30" [ngClass]="{'govuk-input--error': numberControl.errors && numberControl.touched}"
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/phone-uk/write-phone-uk-field.html
> +    <span class="form-label" *ngIf="caseField.label">{{caseField | ccdFieldLabel}}</span>
Whitespace reintroduction.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/phone-uk/write-phone-uk-field.html
> +  <span class="error-message" *ngIf="phoneUkControl.errors && phoneUkControl.touched">{{phoneUkControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/phone-uk/write-phone-uk-field.html
> +  <input class="form-control bottom-30" [ngClass]="{'govuk-input--error': phoneUkControl.errors && phoneUkControl.touched}"
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/text-area/write-text-area-field.html
> +  <span class="error-message" *ngIf="textareaControl.errors && textareaControl.touched">{{textareaControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/text-area/write-text-area-field.html
> +  <textarea (input)="autoGrow($event)" class="form-control bottom-30" [ngClass]="{'govuk-textarea--error': textareaControl.errors && textareaControl.touched}"
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/text/write-text-field.html
> +    <span class="form-label" *ngIf="caseField.label">{{caseField | ccdFieldLabel}}</span>
Whitespace reintroduction.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/text/write-text-field.html
> +  <span class="error-message" *ngIf="textControl.errors && textControl.touched">{{textControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/text/write-text-field.html
> +  <input class="form-control bottom-30" [ngClass]="{'govuk-input--error': textControl.errors && textControl.touched}"
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/utils/first-error.pipe.ts
> -      args = 'Field';
Was this file even in conflict? Everything in here is a regression yet there's nothing _new_! 🤯

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/utils/first-error.pipe.spec.ts
> -import { FirstErrorPipe } from './first-error.pipe';
This makes absolutely no sense! This is `.spec.ts` file yet you've somehow turned it into a pipe and it's now a copy of the (wrong) `FirstErrorPipe`!

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/yes-no/write-yes-no-field.html
> +      <span class="form-label" *ngIf="caseField.label">{{caseField | ccdFieldLabel}}</span>
Whitespace reintroduction.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/components/palette/yes-no/write-yes-no-field.html
> +    <span class="error-message" *ngIf="yesNoControl.errors && yesNoControl.touched">{{yesNoControl.errors | ccdFirstError:caseField.label}}</span>
This is a regression: should be `dirty`, not `touched`.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/directives/conditional-show/conditional-show-form.directive.ts
> -  private handleFormControl = (formControl: FormControl): void => {
Again, nothing has actually changed in here so I can't see where the conflict would be and this simply overwrites what was recently changed in `master`, which included an indentation fix. I personally prefer `c: FormControl` over `formControl: FormControl` (I think I even did that) but this was changed back in `master`.. so this seems like a pointless overwrite.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/services/fields/fields.utils.spec.ts
> -  describe('containsNonEmptyValues() function tests', () => {
This whole `describe` block is new in `master` and shouldn't be removed.

2021-07-01 10:42 UTC, paul-graham commented on src/shared/services/fields/fields.utils.spec.ts
> -    it('should return true for an array with an object containing at least one non-empty descendant value', () => {
This test is new in `master` and shouldn't be removed.

2021-07-01 10:59 UTC, paulhowes-HMCTS commented on src/shared/components/palette/collection/write-collection-field.html
> +    <h2 *ngIf="caseField.hint_text || formArray.errors" class="heading-h2 error-spacing">
@paul-graham I confirm this can be removed as it was code duplicated during PR consolidation.

2021-07-01 11:00 UTC, paul-graham commented on src/shared/components/palette/collection/write-collection-field.html
> +    <h2 *ngIf="caseField.hint_text || formArray.errors" class="heading-h2 error-spacing">
Thanks, @paulhowes-HMCTS. Much appreciated.

2021-07-01 11:59 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.html
> +             (focusout)="focusOut()"
Cancel that. I can see it's being used for something else now.

2021-07-01 12:36 UTC, paul-graham commented on src/shared/components/palette/datetime-picker/datetime-picker.component.ts
> +  public focusOut(): void {
Cancel that. Seems like it's doing something else now.

2021-07-02 08:04 UTC, paul-graham commented on package.json
> +  "version": "4.1.0-rc.3",
Has the suffix for now (for testing) and should be removed prior to merging.

2021-07-02 08:57 UTC, leepavlouhmcts approved these changes

2021-07-16 08:18 UTC, paul-graham approved these changes
The changes since I last approved this look to be perfectly reasonable. So approving it again.

2021-07-16 08:32 UTC, leepavlouhmcts approved these changes

2021-07-16 09:40 UTC, merged